apiVersion: v1
kind: Pod
metadata:
 name: environament
spec:
 containers:
 - name: nginx
   image: nginx
   env:
   - name: course
     value: "devops with aws"
   - name: trainer
     value: "sivakumar reddy"
   - name: duration
     value: "120 hours"