apiVersion: v1
kind: Service 
metadata: 
 name: ngiNx
spec:
 selector:
   project: expense
   module: backend
   environment: dev
 ports:
   - name: nginx-svc-port
     protocal: TCP
     port: 80 # service port
     targetPort: 80 # container port
